name: weatherx
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: 4.0.0
  http: ^0.13.3
  intl: ^0.17.0
  shared_preferences: ^2.0.6
  font_awesome_flutter:
  connectivity : 2.0.2
  flutter_launcher_icons: ^0.9.1


flutter_icons:
  image_path_android: "assets/images/weatherx.png"
  image_path_ios: "assets/images/weatherx.png"
  android: true 
  ios: true 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/json/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
